alias vim='nvim'
alias cls='clear'
alias tmux='tmux -u'
alias src='source ~/.bashrc'
alias zsrc='source ~/.zshrc'
alias ctf='mkdir pwn foren rev web misc crypto osint'
alias ..='cd ..'
alias ...='cd ../..'
alias mv='mv -i'
# alias rm='rm -i'
alias xclip='xclip -sel clip'
alias sdn='shutdown now'
alias rbt='sudo reboot now'
alias ls='exa'
alias rustscan='sudo docker run rustscan'
alias ydl='youtube-dl'
CNG_PATH='/home/raahil/courses/sem5/iot/grp_proj/contiki-ng'
alias contiker="sudo docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --mount type=bind,source=$CNG_PATH,destination=/home/user/contiki-ng -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/bus/usb:/dev/bus/usb -ti contiker/contiki-ng"
